import Model from '../dataModel/model';
import { Context, Plugin } from './interface';
import WhereInputPlugin from './whereInput';
import BaseTypePlugin from './baseType';
import ObjectField from '../dataModel/objectField';
import { upperFirst, forEach } from 'lodash';
import { ListMutable } from '../dataSource/interface';

const createObjectInputField = (prefix: string, field: ObjectField, context: Context) => {
  const { root } = context;
  const content: string[] = [];
  forEach(field.getFields(), (nestedField, name) => {
    if (nestedField.isScalar()) {
      content.push(`${name}: ${nestedField.getTypename()}`);
      return;
    }

    if (nestedField instanceof ObjectField) {
      const fieldWithPrefix = `${prefix}${upperFirst(name)}`;
      const typeFields = createObjectInputField(fieldWithPrefix, nestedField, context);
      const objectInputName = `${fieldWithPrefix}CreateInput`;
      root.addInput(`input ${objectInputName} {${typeFields.join(' ')}}`);
      content.push(`${name}: ${objectInputName}`);
      return;
    }

    // skip relation field
  });
  return content;
};

const createInputField = (model: Model, context: Context) => {
  const { root } = context;
  const fields = model.getFields();
  const content: string[] = [];
  forEach(fields, (field, name) => {
    if (field.isAutoGenerated()) {
      return;
    }

    if (field.isScalar()) {
      content.push(`${name}: ${field.getTypename()}`);
      return;
    }

    if (field instanceof ObjectField) {
      // create input for nested object
      const fieldWithPrefix = `${model.getNamings().capitalSingular}${upperFirst(name)}`;
      const typeFields = createObjectInputField(fieldWithPrefix, field, context);
      const objectInputName = `${fieldWithPrefix}CreateInput`;
      root.addInput(`input ${objectInputName} {${typeFields.join(' ')}}`);
      content.push(`${name}: ${objectInputName}`);
      return;
    }

    // todo: add relation
  });

  return content;
};

export default class CreatePlugin implements Plugin {
  private whereInputPlugin: WhereInputPlugin;
  private baseTypePlugin: BaseTypePlugin;
  private beforeCreate?: (data: Record<string, any>) => Promise<void>;
  private transformPayload?: (data: Record<string, any>) => Promise<Record<string, any>>;
  private afterCreate?: (data: Record<string, any>) => Promise<void>;

  constructor({
    beforeCreate,
    transformPayload,
    afterCreate,
  }: {
    beforeCreate?: (data: Record<string, any>) => Promise<void>,
    transformPayload?: (data: Record<string, any>) => Promise<Record<string, any>>,
    afterCreate?: (data: Record<string, any>) => Promise<void>,
  }) {
    this.beforeCreate = beforeCreate;
    this.transformPayload = transformPayload;
    this.afterCreate = afterCreate;
  }

  public setPlugins(plugins: Plugin[]) {
    this.whereInputPlugin = plugins.find(
      plugin => plugin instanceof WhereInputPlugin) as WhereInputPlugin;
    this.baseTypePlugin = plugins.find(
      plugin => plugin instanceof BaseTypePlugin) as BaseTypePlugin;
  }

  public visitModel(model: Model, context: Context) {
    const { root } = context;
    const modelType = this.baseTypePlugin.getTypename(model);

    // create
    const mutationName = this.getInputName(model);
    const inputName = this.generateCreateInput(model, context);
    root.addMutation(`${mutationName}(data: ${inputName}!): ${modelType}`);
  }

  public resolveInMutation({model, dataSource}: {model: Model, dataSource: ListMutable}) {
    const mutationName = this.getInputName(model);
    return {
      [mutationName]: async (root, args, context) => {
        if (this.beforeCreate) {
          await this.beforeCreate(args.data);
        }
        const data = this.transformPayload ? await this.transformPayload(args.data) : args.data;
        const created = await dataSource.create(data);
        if (this.afterCreate) {
          await this.afterCreate(data);
        }
        return created;
      },
    };
  }

  private generateCreateInput(model: Model, context: Context) {
    const inputName = `${model.getNamings().capitalSingular}CreateInput`;
    const input = `input ${inputName} {
      ${createInputField(model, context)}
    }`;
    context.root.addInput(input);
    return inputName;
  }

  private getInputName(model: Model) {
    return `create${model.getNamings().capitalSingular}`;
  }
}
